services:
  - type: web
    name: fincore-auth-service
    env: docker
    dockerfilePath: auth-service/Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8081

  - type: web
    name: fincore-user-service
    env: docker
    dockerfilePath: user-service/Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: PORT
        value: 8082

  - type: web
    name: fincore-account-service
    env: docker
    dockerfilePath: account-service/Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: PORT
        value: 8083

  - type: web
    name: fincore-transaction-service
    env: docker
    dockerfilePath: transaction-service/Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: SPRING_RABBITMQ_ADDRESSES
        sync: false
      - key: ACCOUNT_SERVICE_URL
        fromService:
          type: web
          name: fincore-account-service
          property: url
      - key: PORT
        value: 8084

  - type: web
    name: fincore-notification-service
    env: docker
    dockerfilePath: notification-service/Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: SPRING_RABBITMQ_ADDRESSES
        sync: false
      - key: PORT
        value: 8085

  - type: web
    name: fincore-api-gateway
    env: docker
    dockerfilePath: api-gateway/Dockerfile
    envVars:
      - key: AUTH_SERVICE_URL
        fromService:
          type: web
          name: fincore-auth-service
          property: url
      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: fincore-user-service
          property: url
      - key: ACCOUNT_SERVICE_URL
        fromService:
          type: web
          name: fincore-account-service
          property: url
      - key: TRANSACTION_SERVICE_URL
        fromService:
          type: web
          name: fincore-transaction-service
          property: url
      - key: NOTIFICATION_SERVICE_URL
        fromService:
          type: web
          name: fincore-notification-service
          property: url
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080