server:
  port: 8083

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb+srv://kim:alinemongo%401@cluster0.0jrqyub.mongodb.net/account_db}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html